baseURL: "https://nickkarpov.com"
languageCode: "en-US"
title: "Nick Karpov"

defaultContentLanguage: en-us

menu:
  footer:
    - name: "about"
      url: "/about"
      weight: 1
    - name: "archives"
      url: "/archives/"
      weight: 2
    - name: "categories"
      url: "/categories/"
      weight: 3
    - name: "tags"
      url: "/tags/"
      weight: 4

  icon:
    - name: "rss"
      url: "/index.xml"
      weight: 1
    - name: "twitter"
      url: "https://x.com/nickkarpov"
      weight: 2

markup:
  highlight:
    style: friendly
    guessSyntax: true
  goldmark:
    extensions:
      typographer:
        disable: true
    renderer:
      unsafe: true

# Site.params
params:
  smartToc: true
  author: Nick Karpov
  keywords:
    - Technology
    - Code
    - Program
    - Linux
  description: "LLMs make you stupid"

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"

summaryLength: 500
hasCJKLanguage: true
outputs:
  home: ["html", "rss"]

pagination:
  pagerSize: 10
